### ISSUE TITLE
Mod update for Release v rising

### ISSUE THREAD

**Issue by IBlackHerO** [caioreix/BetterMissions#11]
Good afternoon. Can you tell me - will the mod be updated for the release version v rising?

**Comment by caioreix** [comment]
Yes ill update asap

**Comment by IBlackHerO** [comment]
Thank you very much.

**Comment by IBlackHerO** [comment]
Good afternoon. I see you have updated the mod, but the problem is that it does not work. I threw in the files that you posted + put Bloodstone-0.2.2, in the configuration file BetterMissions, I change the parameter MissionLengthModifier and the mission time is not reduced.
Maybe I'm doing something wrong? Thank you very much in advance.

**Comment by caioreix** [comment]
Did u extract the 3 dlls: vrising-utils.dll, bepinex-utils.dll BetterMissions.dll?

**Comment by IBlackHerO** [comment]
Yes. I put all these 3 files in the plugins folder. At the stage of initialization of mods in BepInEx there are
![image](https://github.com/caioreix/BetterMissions/assets/134227786/805ca596-b766-4dc7-bd7c-406d60d63c60)
 no errors either.

**Comment by caioreix** [comment]
Better Missions is an server side mod did u installed in the server too? You can easily install using [Server Launch Fix](https://thunderstore.io/c/v-rising/p/Mythic/ServerLaunchFix/)

**Comment by IBlackHerO** [comment]
Completely forgot about Server Launch Fix. Thank you.
