### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by IBlackHerO** [caioreix/BetterMissions#7]
Good afternoon. Can you update your mod?  BepInEx has already been updated. https://github.com/decaprime/VRising-Modding/releases/tag/0.668.001

**Comment by caioreix** [comment]
This weekend I'll take a look, from what I'm told now time counts offline natively, but I haven't confirmed yet

**Comment by IBlackHerO** [comment]
You are right. The time is now counted off-line. Thank you very much in advance.

**Comment by IBlackHerO** [comment]
> В эти выходные я посмотрю, из того, что мне сказали, сейчас время считается в автономном режиме изначально, но я еще не подтвердил

Так у вас получится обновить

**Comment by IBlackHerO** [comment]
Will you be able to update the mod?

**Comment by caioreix** [comment]
I will update it, but I'm out of time. I took a look, and they changed a lot of things. It won't be a simple migration to Gloomrot. First, I'll update to enable the settings, and then I'll see if I can add offline functionality for the servants.

**Comment by leion247** [comment]
Note, Wetstone is no longer supported. Most likely will need to migrate over to Bloodstone instead since that replaces it. Otherwise there may be further issues down the line after updating.

**Comment by caioreix** [comment]
Updated in #8. If you find any errors, feel free to open a new issue.
